import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, ClipboardCheck, Coins, MessageSquare, UsersRound } from "lucide-react";
import { PublicFooter, PublicNav } from "@/components/PublicSite";

const modules = [
  { icon: UsersRound, title: "Student information", text: "Admissions, guardians, classes, placements and complete student records." },
  { icon: BookOpen, title: "Academics", text: "Curriculum, subjects, assessments, report cards and academic progress." },
  { icon: ClipboardCheck, title: "Attendance & welfare", text: "Daily attendance, discipline, safeguarding, library and transport workflows." },
  { icon: Coins, title: "Fees & accounting", text: "Invoices, payments, feeding fees, scholarships, cashbook and reports." },
  { icon: MessageSquare, title: "Communication", text: "Targeted announcements, parent notifications and Ghana-ready SMS." },
  { icon: BarChart3, title: "Actionable insights", text: "Exportable reports that help school leaders make faster decisions." },
];

export default function Home() {
  return <main className="min-h-screen bg-[#f5fbf7] text-slate-950">
    <PublicNav />
    <section className="relative overflow-hidden border-y border-[#dcefe2] bg-white">
      <div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-[#fcd116]/20 blur-3xl" />
      <div className="absolute -bottom-32 -left-20 h-80 w-80 rounded-full bg-[#006b3f]/10 blur-3xl" />
      <div className="relative mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-28">
        <div><span className="inline-flex rounded-full border border-[#bfe2cc] bg-[#effaf2] px-3 py-1.5 text-xs font-bold uppercase tracking-[0.14em] text-[#006b3f]">School management, made simple</span><h1 className="mt-6 max-w-3xl text-5xl font-extrabold leading-[1.05] tracking-tight sm:text-6xl">Everything your school needs to thrive.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Heisen SchoolOS brings your people, academics, finance and daily operations into one secure workspace built for Ghanaian schools.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-[#006b3f] px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-emerald-900/15 hover:bg-[#005530]">Start managing your school <ArrowRight className="h-4 w-4" /></Link><Link href="/pricing" className="rounded-xl border border-[#cfe4d5] bg-white px-5 py-3.5 text-sm font-bold text-[#006b3f] hover:bg-[#effaf2]">Explore plans</Link></div><p className="mt-5 text-xs font-medium text-slate-500">Secure access · Ghanaian curriculum · Parent-ready communication</p></div>
        <div className="relative rounded-3xl border border-[#d8ebde] bg-[#f1faf3] p-4 shadow-2xl shadow-emerald-950/10 sm:p-6"><div className="rounded-2xl bg-[#111] p-5 text-white sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-emerald-300">SchoolOS overview</p><p className="mt-2 text-xl font-bold">Your school at a glance</p></div><span className="rounded-lg bg-[#006b3f] px-2.5 py-1.5 text-xs font-bold">Live</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-slate-400">Attendance</p><p className="mt-2 text-2xl font-bold">94.8%</p><div className="mt-2 h-1.5 rounded-full bg-emerald-400" /></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-slate-400">Collections</p><p className="mt-2 text-2xl font-bold">GHS 48k</p><div className="mt-2 h-1.5 rounded-full bg-[#fcd116]" /></div><div className="col-span-2 rounded-xl bg-white/10 p-4"><div className="flex items-center justify-between text-xs"><span className="text-slate-400">Today&apos;s operations</span><span className="text-emerald-300">On track</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-white/10 px-2 py-3">Classes<br /><b className="text-base text-white">24</b></span><span className="rounded-lg bg-white/10 px-2 py-3">Staff<br /><b className="text-base text-white">38</b></span><span className="rounded-lg bg-white/10 px-2 py-3">Tasks<br /><b className="text-base text-white">12</b></span></div></div></div></div></div>
      </div>
    </section>
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#006b3f]">One connected platform</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">From first admission to final report card.</h2><p className="mt-4 text-slate-600">Replace disconnected spreadsheets and manual follow-up with workflows your whole school can use.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-[#dcefe2] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e9f7ed] text-[#006b3f]"><Icon className="h-5 w-5" /></div><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></section>
    <section className="bg-[#006b3f] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-6 py-14 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><p className="text-2xl font-extrabold">Ready to run a better school?</p><p className="mt-2 text-sm text-emerald-100">Set up your workspace and bring your team together.</p></div><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-[#fcd116] px-5 py-3 font-bold text-slate-950 hover:bg-[#ffe36b]">Create your school <ArrowRight className="h-4 w-4" /></Link></div></section>
    <PublicFooter />
  </main>;
}
