"use client";
import { useActionState } from "react";
import { createCalendarEvent, createNotificationAutomation } from "../operations/actions";
const initial = null;
export default function CalendarForms() {
  const [eventState, eventAction] = useActionState(createCalendarEvent, initial);
  const [ruleState, ruleAction] = useActionState(createNotificationAutomation, initial);
  return <div className="grid gap-6 lg:grid-cols-2">
    <form action={eventAction} className="space-y-3 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Add calendar event</h2><input name="title" required placeholder="Event title" className="w-full rounded-lg border p-2.5 text-sm" /><select name="type" className="w-full rounded-lg border p-2.5 text-sm"><option value="academic">Academic</option><option value="holiday">Holiday</option><option value="meeting">Meeting</option><option value="activity">Activity</option><option value="deadline">Deadline</option><option value="other">Other</option></select><div className="grid grid-cols-2 gap-2"><input name="startsAt" type="datetime-local" required className="rounded-lg border p-2.5 text-sm" /><input name="endsAt" type="datetime-local" required className="rounded-lg border p-2.5 text-sm" /></div><textarea name="description" placeholder="Description (optional)" className="w-full rounded-lg border p-2.5 text-sm" /><label className="flex gap-2 text-sm"><input type="checkbox" name="allDay" /> All day</label><button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Create event</button>{eventState?.error && <p className="text-sm text-red-600">{eventState.error}</p>}{eventState?.success && <p className="text-sm text-green-700">{eventState.success}</p>}</form>
    <form action={ruleAction} className="space-y-3 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Notification automation</h2><input name="name" required placeholder="Reminder name" className="w-full rounded-lg border p-2.5 text-sm" /><select name="trigger" className="w-full rounded-lg border p-2.5 text-sm"><option value="calendar_event">Calendar event reminder</option><option value="leave_request">Leave request alert</option></select><input name="daysBefore" type="number" min="0" max="30" defaultValue="1" className="w-full rounded-lg border p-2.5 text-sm" /><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Enable automation</button>{ruleState?.error && <p className="text-sm text-red-600">{ruleState.error}</p>}{ruleState?.success && <p className="text-sm text-green-700">{ruleState.success}</p>}</form>
  </div>;
}
